<a href="https://colab.research.google.com/github/iishachoudhary/ML-lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
arr = np.array([1, 2, 3, 4, 5])

print("1D Array:", arr)

1D Array: [1 2 3 4 5]


In [2]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("\n2D Array:")
print(arr_2d)


2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
#LIST TO ARRAY
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [5]:
#Operations on array

my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")

#ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Dimension of this matrix: ",mat.ndim,sep='')

 #size gives the total number of elements
print("Size of this matrix: ", mat.size,sep='')

#shape gives the number of elements along each axes (dimension)
print("Shape of this matrix: ", mat.shape,sep='')

#dtype gives the data type contained in the array
print("Data type of this matrix: ", mat.dtype,sep='')

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [14]:
#NP.ARRANGE
# np.arrange(a,b) = A series of numbers from a to b
print("A series of numbers:",np.arange(5,16))

# np.arrange(a,b,c) =  A series of numbers from a to b spaced apart by c
print("\n Numbers spaced apart by 2:",np.arange(0,11,2))

# np.arrange(m,-n,-o) = m to n spaced by -o
print("\n Every 5th number from 50 in reverse order",np.arange(50,-1,-5))



A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]

 Numbers spaced apart by 2: [ 0  2  4  6  8 10]

 Every 5th number from 50 in reverse order [50 45 40 35 30 25 20 15 10  5  0]


In [15]:
#linspace
print("21 linearly spaced numbers between 1 and 5\n")
print(np.linspace(1,5,21))

21 linearly spaced numbers between 1 and 5

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


In [16]:
# Generate a random integer between 0 and 10 (exclusive)
rand_int = np.random.randint(0, 10)
print(rand_int)

# Generate a random float between 0 and 1
rand_float = np.random.rand()
print(rand_float)

# Generate a 1D array of 5 random floats between 0 and 1
rand_array = np.random.rand(5)
print(rand_array)


9
0.8612740673838615
[0.09366087 0.7772639  0.9880041  0.38724127 0.14969098]


In [21]:
# Print a 1D array of 5 zeros directly
print("1D Array of Zeros:", np.zeros(5))

# Print a 2D array (3x4) of zeros directly
print("\n 2D Array of Zeros:\n", np.zeros((3, 4)))

# Print a 2D array (3x3) of zeros with integer data type directly
print("\n 2D Array of Zeros (Integer Type):\n", np.zeros((3, 3), dtype=int))

# Print a 3D array (2x3x4) of zeros directly
print("\n 3D Array of Zeros:\n", np.zeros((2, 3, 4)))


1D Array of Zeros: [0. 0. 0. 0. 0.]

 2D Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 2D Array of Zeros (Integer Type):
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

 3D Array of Zeros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [26]:
# Print a 1D array of 5 ones directly
print("1D Array of Ones:", np.ones(5))

# Print a 2D array (3x4) of ones directly
print("\n 2D Array of Ones:\n", np.ones((3, 4)))

# Print a 2D array (3x3) of ones with integer data type directly
print("\n 2D Array of Ones (Integer Type):\n", np.ones((3, 3), dtype=int))

# Print a 3D array (2x3x4) of ones directly
print("\n 3D Array of Ones:\n", np.ones((2, 3, 4)))


1D Array of Ones: [1. 1. 1. 1. 1.]

 2D Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 2D Array of Ones (Integer Type):
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

 3D Array of Ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [25]:
# np.eye(3) = Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#np.reshape
# Create a 1D array of 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape it to a 2D array of shape (2, 3)
reshaped_arr = np.reshape(arr, (2, 3))
print("Reshaped Array (2x3):\n", reshaped_arr)


Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
